data:
  train_root_A: ./data/HER2match/HE/train
  train_root_B: ./data/HER2match/IHC/train
  valid_root_A: ./data/HER2match/HE/val
  valid_root_B: ./data/HER2match/IHC/val
  train_mask_root_B: ./data/HER2match/mask
  num_workers: 16

training:
  world_size: 4
  batch_size: 3
  lr: 0.0001
  img_size: 1024

  lambda_l1: 10.0
  lambda_stain: 25.0
  lambda_cls: 2.0
  lambda_seg: 2.0
  lambda_gan: 1.0
  lambda_per: 0.5

  warm_epochs: 10
  decay_epochs: 90
  num_epochs: 200

  save_dir: ./output/checkpoints

  val_freq: 10
  load_module: False
  checkpoint_path: ./checkpoints

testing:
  image_size: 1024
  currentepoch: 156
  test_root_A: ./data/HER2match/HE/test
  test_root_B: ./data/HER2match/IHC/test
  save_path: ./checkpoints/
  test_output_dir: ./inference

validing:
  valid_output_dir: ./output/valid_output
  csv_path: ./output/valid/metrics.csv